name: Publish

on:
  push:
    paths:
      - .github/workflows/publish.yml
      - library/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: |
          ./gradlew :library:publish -Pversion=${GITHUB_REF##*/}-SNAPSHOT
          ./gradlew :library:publish -Pversion=$(git rev-parse --short "$GITHUB_SHA")
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}